services:
  # Backend Service
  backend:
    build: .
    container_name: mental_health_backend
    environment:
      - NODE_ENV=development
      - DATABASE_URL=${DATABASE_URL}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - GOOGLE_AI_API_KEY=${GOOGLE_AI_API_KEY}
      - PORT=3001
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    restart: unless-stopped

  # Frontend Service
  frontend:
    build: ./frontend
    container_name: mental_health_frontend
    environment:
      - VITE_CLERK_PUBLISHABLE_KEY=${VITE_CLERK_PUBLISHABLE_KEY}
      - VITE_API_BASE_URL=http://localhost:3001/api
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  node_modules: