// persona-observer.ts (Persona Selection Observer)
import { GoogleGenerativeAI } from "@google/generative-ai";
import { zValidator } from "@hono/zod-validator";
import fs from "fs";
import { Hono } from "hono";
import path from "path";
import { z } from "zod";
import { geminiConfig } from "../lib/config";
import { logger } from "../lib/logger";

// Initialize Gemini
const gemini = new GoogleGenerativeAI(process.env.GEMINI_API_KEY!);

// Load personas configuration
let personasConfig: any = null;
const loadPersonasConfig = async () => {
  try {
    const personasPath = path.join(process.cwd(), "personas.json");
    const personasData = await fs.promises.readFile(personasPath, "utf8");
    personasConfig = JSON.parse(personasData);
  } catch (error) {
    logger.error("Error loading personas config:", error);
    // Fallback to basic persona structure
    personasConfig = {
      personas: {
        listener: {
          id: "listener",
          name: "Empathetic Listener",
          systemInstruction: "You are an empathetic listener who provides a safe space for users to share their feelings.",
          triggers: ["need someone to talk to", "feeling overwhelmed", "need support"],
          emotionalIndicators: ["sadness", "loneliness", "stress"]
        }
      },
      selectionRules: {
        priorityOrder: ["listener"],
        fallbackPersona: "listener"
      }
    };
  }
};

// Initialize personas config
loadPersonasConfig();

// Persona observer logging function
const logPersonaObserverCall = async (
  messages: { text: string; sender: string }[],
  selectedPersona: string,
  analysis: {
    sentiment: string;
    detectedNeeds: string[];
    confidence: number;
    rationale: string;
  },
  initialForm?: {
    preferredName?: string;
    currentEmotions?: string[];
    reasonForVisit?: string;
    supportType?: string[];
    additionalContext?: string;
  }
) => {
  try {
    const logsDir = path.join(process.cwd(), "persona_observer_logs");
    await fs.promises.mkdir(logsDir, { recursive: true });

    const now = new Date();
    const dateStr = now.toISOString().split("T")[0];
    const timeStr = now
      .toLocaleTimeString("en-US", {
        hour12: true,
        hour: "numeric",
        minute: "2-digit",
        second: "2-digit",
      })
      .replace(/:/g, "-")
      .replace(/\s/g, "_");
    const filename = `${dateStr}_at_${timeStr}.md`;
    const filepath = path.join(logsDir, filename);

    const logContent = `# Persona Observer Call Log - ${dateStr} at ${timeStr}

## Input Messages
${messages
  .map(
    (msg, index) => `### Message ${index + 1}
**Sender:** ${msg.sender}
**Text:** ${msg.text}
`
  )
  .join("\n")}

## Initial Form Data
${
  initialForm
    ? `
- **Preferred Name:** ${initialForm.preferredName || "Not provided"}
- **Current Emotions:** ${initialForm.currentEmotions?.join(", ") || "Not provided"}
- **Reason for Visit:** ${initialForm.reasonForVisit || "Not provided"}
- **Support Type:** ${initialForm.supportType?.join(", ") || "Not provided"}
- **Additional Context:** ${initialForm.additionalContext || "Not provided"}
`
    : "No initial form data provided"
}

## Persona Selection Analysis
### Selected Persona
${selectedPersona}

### Sentiment Analysis
${analysis.sentiment}

### Detected Needs
${analysis.detectedNeeds.map((need, index) => `${index + 1}. ${need}`).join("\n")}

### Confidence Score
${analysis.confidence}/100

### Rationale for Selection
${analysis.rationale}

---
*Generated by Persona Observer API at ${now.toISOString()}*
`;

    await fs.promises.writeFile(filepath, logContent, "utf8");
  } catch (error) {
    logger.error("❌ Error saving persona observer log:", error);
  }
};

// Define schema for persona observer request
export const personaObserverRequestSchema = z.object({
  messages: z.array(
    z.object({
      text: z.string(),
      sender: z.enum(["user", "ai"]),
    })
  ),
  initialForm: z
    .object({
      preferredName: z.string().optional(),
      currentEmotions: z.array(z.string()).optional(),
      reasonForVisit: z.string().optional(),
      supportType: z.array(z.string()).optional(),
      additionalContext: z.string().optional(),
    })
    .optional(),
});

export const personaObserverResponseSchema = z.object({
  selectedPersona: z.string(),
  personaName: z.string(),
  systemInstruction: z.string(),
  sentiment: z.string(),
  detectedNeeds: z.array(z.string()),
  confidence: z.number(),
  rationale: z.string(),
});

const personaObserver = new Hono().post(
  "/",
  zValidator("json", personaObserverRequestSchema),
  async (c) => {
    const parsed = personaObserverRequestSchema.safeParse(await c.req.json());
    if (!parsed.success) {
      logger.error("Persona Observer Zod validation error:", parsed.error.errors);
      return c.json({ error: JSON.stringify(parsed.error.errors) }, 400);
    }

    const { messages, initialForm } = parsed.data;

    try {
      // Reload personas config to get latest updates
      await loadPersonasConfig();
      
      // Analyze and select appropriate persona
      const result = await selectPersona(messages, initialForm);

      // Log the observer call
      await logPersonaObserverCall(
        messages,
        result.selectedPersona,
        {
          sentiment: result.sentiment,
          detectedNeeds: result.detectedNeeds,
          confidence: result.confidence,
          rationale: result.rationale,
        },
        initialForm
      );

      return c.json(result);
    } catch (error) {
      logger.error("Error in persona observer analysis:", error);
      // Fallback to listener persona
      const fallbackPersona = personasConfig?.personas?.listener || {
        id: "listener",
        name: "Empathetic Listener",
        systemInstruction: "You are an empathetic listener who provides a safe space for users to share their feelings."
      };
      
      return c.json({
        selectedPersona: "listener",
        personaName: fallbackPersona.name,
        systemInstruction: fallbackPersona.systemInstruction,
        sentiment: "neutral",
        detectedNeeds: ["emotional support"],
        confidence: 50,
        rationale: "Error in analysis, defaulting to empathetic listener persona",
      });
    }
  }
);

// --- Persona Selection Logic ---
async function selectPersona(
  messages: { text: string; sender: string }[],
  initialForm?: {
    preferredName?: string;
    currentEmotions?: string[];
    reasonForVisit?: string;
    supportType?: string[];
    additionalContext?: string;
  }
): Promise<{
  selectedPersona: string;
  personaName: string;
  systemInstruction: string;
  sentiment: string;
  detectedNeeds: string[];
  confidence: number;
  rationale: string;
}> {
  const model = gemini.getGenerativeModel({
    model: geminiConfig.twoPoint5FlashLite,
  });

  // Build context string
  let contextString = "";
  if (initialForm) {
    if (initialForm.preferredName)
      contextString += `User's preferred name: ${initialForm.preferredName}\n`;
    if (initialForm.currentEmotions && initialForm.currentEmotions.length > 0) {
      contextString += `User's current emotions: ${initialForm.currentEmotions.join(
        ", "
      )}\n`;
    }
    if (initialForm.reasonForVisit)
      contextString += `User's reason for visit: ${initialForm.reasonForVisit}\n`;
    if (initialForm.supportType && initialForm.supportType.length > 0) {
      contextString += `User's desired support type: ${initialForm.supportType.join(
        ", "
      )}\n`;
    }
    if (initialForm.additionalContext)
      contextString += `Additional context: ${initialForm.additionalContext}\n`;
  }

  // Get recent conversation
  const recentMessages = messages.slice(-5);
  const conversationText = recentMessages
    .map((msg) => `${msg.sender === "user" ? "User" : "AI"}: ${msg.text}`)
    .join("\n");

  // Create available personas summary for the AI
  const personasSummary = Object.values(personasConfig.personas)
    .map((persona: any) => `- ${persona.id}: ${persona.name} - ${persona.description}`)
    .join("\n");

  const prompt = `You are a persona selection AI that analyzes user conversations to choose the most appropriate AI persona for their needs.

Available Personas:
${personasSummary}

Context about the user:
${contextString}

Recent conversation:
${conversationText}

Analyze the user's emotional state, needs, and communication style to select the best persona. Consider:
1. Their emotional state and immediate needs
2. The type of support they're seeking
3. Their communication style and preferences
4. Any signs of crisis or urgent need

Respond in this exact JSON format:
{
  "sentiment": "positive|negative|neutral|urgent|confused|crisis_risk",
  "detectedNeeds": ["need1", "need2", "need3"],
  "recommendedPersona": "persona_id",
  "confidence": 85,
  "rationale": "Detailed explanation of why this persona is best suited for the user"
}

Priority rules:
- If crisis_risk or urgent detected, prioritize crisis support
- If user needs emotional validation and listening, prioritize listener
- If user seeks advice and solutions, prioritize guide
- If user wants distraction and light conversation, prioritize companion
- Default to listener if unsure`;

  const result = await model.generateContent(prompt);
  const response = result.response.text();

  try {
    const jsonMatch = response.match(/\{[\s\S]*\}/);
    if (!jsonMatch) {
      throw new Error("No JSON found in response");
    }

    const parsed = JSON.parse(jsonMatch[0]);
    const recommendedPersonaId = parsed.recommendedPersona || "listener";
    const selectedPersona = personasConfig.personas[recommendedPersonaId] || personasConfig.personas.listener;

    return {
      selectedPersona: selectedPersona.id,
      personaName: selectedPersona.name,
      systemInstruction: selectedPersona.systemInstruction,
      sentiment: parsed.sentiment || "neutral",
      detectedNeeds: Array.isArray(parsed.detectedNeeds) ? parsed.detectedNeeds : ["emotional support"],
      confidence: typeof parsed.confidence === "number" ? parsed.confidence : 50,
      rationale: parsed.rationale || "Selected based on user's emotional needs and communication style",
    };
  } catch (parseError) {
    logger.error("Error parsing persona selection response:", parseError);
    logger.error("Raw response:", response);

    // Fallback to listener persona
    const fallbackPersona = personasConfig.personas.listener;
    return {
      selectedPersona: fallbackPersona.id,
      personaName: fallbackPersona.name,
      systemInstruction: fallbackPersona.systemInstruction,
      sentiment: "neutral",
      detectedNeeds: ["emotional support"],
      confidence: 50,
      rationale: "Error in analysis, defaulting to empathetic listener persona",
    };
  }
}

export default personaObserver;
export type PersonaObserverType = typeof personaObserver;