/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PodcastImport } from './routes/podcast'
import { Route as ImpersonateImport } from './routes/impersonate'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const PodcastRoute = PodcastImport.update({
  id: '/podcast',
  path: '/podcast',
  getParentRoute: () => rootRoute,
} as any)

const ImpersonateRoute = ImpersonateImport.update({
  id: '/impersonate',
  path: '/impersonate',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/impersonate': {
      id: '/impersonate'
      path: '/impersonate'
      fullPath: '/impersonate'
      preLoaderRoute: typeof ImpersonateImport
      parentRoute: typeof rootRoute
    }
    '/podcast': {
      id: '/podcast'
      path: '/podcast'
      fullPath: '/podcast'
      preLoaderRoute: typeof PodcastImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/impersonate': typeof ImpersonateRoute
  '/podcast': typeof PodcastRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/impersonate': typeof ImpersonateRoute
  '/podcast': typeof PodcastRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/impersonate': typeof ImpersonateRoute
  '/podcast': typeof PodcastRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/impersonate' | '/podcast'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/impersonate' | '/podcast'
  id: '__root__' | '/' | '/impersonate' | '/podcast'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImpersonateRoute: typeof ImpersonateRoute
  PodcastRoute: typeof PodcastRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImpersonateRoute: ImpersonateRoute,
  PodcastRoute: PodcastRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/impersonate",
        "/podcast"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/impersonate": {
      "filePath": "impersonate.tsx"
    },
    "/podcast": {
      "filePath": "podcast.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
